refactoring script to more readable approach

diff --git a/easy b/easy
--- a/easy
+++ b/easy
@@ -10,6 +10,7 @@ prepare_docker() {
     # Build the docker image
     cd "$PROJECT_DIR/docker"
     docker build -t easyaccept .
+    cd "$PROJECT_DIR"
 }
 
 prepare_grammar() {
@@ -37,60 +38,136 @@ antlr4_parse() {
     java -cp /usr/local/lib/antlr4-tool.jar:.tmp/grammar/target/ org.antlr.v4.gui.TestRig "$@"
 }
 
-help() {
-    echo
-    echo "Usage:  $0 COMMAND"
-    echo
-    echo "Commands:"
-    echo "  generate:csharp   Generate the grammar in C#"
-    echo "  tree              Parse the grammar and print the parse tree"
-    echo "  help              Display this help message"
-    echo
+parse_arguments() {
+    local help_requested=0
+    local command_requested=""
+
+    while [[ -z "$command_requested" && "$#" -gt 0 ]]; do
+        case $1 in
+            -h|--help)
+                help_requested=1
+                shift
+                ;;
+            *)
+                command_requested=$1
+                shift
+                break
+                ;;
+        esac
+    done
+
+    if [[ $help_requested -eq 1 ]]; then
+        case $command_requested in
+            generate)
+                echo "Usage: ./easy generate <language> [-o | --output <output_directory>]"
+                echo
+                echo "Generate the grammar on specified language. Supported languages: csharp"
+                echo "Can specify output directory with -o or --output option."
+                ;;
+            tree)
+                echo "Usage: ./easy tree"
+                echo
+                echo "Parse the grammar and print the parse tree."
+                ;;
+            *)
+                echo "Usage: ./easy [-h | --help] <command> [<args>]"
+                echo
+                echo "Commands:"
+                echo "  generate   Generate the grammar on specified language"
+                echo "  tree       Parse the grammar and print the parse tree"
+                ;;
+        esac
+
+        exit
+    fi
+
+    if [[ -z "$command_requested" ]]; then
+        echo "Error: No command provided."
+        echo "Use -h or --help for usage information."
+        exit 1
+    fi
+
+    case $command_requested in
+        generate)
+            if [[ "$#" -lt 1 ]]; then
+                echo "Error: No language provided for 'generate' command."
+                echo "Use -h or --help for usage information."
+                exit 1
+            fi
+
+            local language=$1
+            shift
+
+            local output_directory=""
+
+            while [[ "$#" -gt 0 ]]; do
+                case $1 in
+                    -o|--output)
+                        if [[ "$#" -lt 2 ]]; then
+                            echo "Error: No output directory provided after '$1'."
+                            echo "Use -h or --help for usage information."
+                            exit 1
+                        fi
+                        output_directory=$2
+                        shift 2
+                        ;;
+                    *)
+                        echo "Error: Unknown option '$1' for 'generate' command."
+                        echo "Use -h or --help for usage information."
+                        exit 1
+                        ;;
+                esac
+            done
+
+            if [[ "$language" == "csharp" ]]; then
+                prepare_docker
+                prepare_grammar
+
+                # Generate the grammar as C# files
+                antlr4 -Dlanguage=CSharp -o .tmp/grammar/csharp /work/EasyScript.g4
+
+                # Move generated files to output directory if specified
+                if [[ -n "$output_directory" ]]; then
+                    mv .tmp/grammar/csharp "$output_directory"
+                    echo "C# grammar files have been generated in '""$output_directory""'."
+                else
+                    echo "C# grammar files have been generated in '.tmp/grammar/csharp'."
+                fi
+
+                exit 0
+            else
+                echo "Error: Unsupported language '$language' for 'generate' command."
+                echo "Use -h or --help for usage information."
+                exit 1
+            fi
+            ;;
+        tree)
+            prepare_docker
+            prepare_grammar
+
+            # Generate the grammar as Java files
+            antlr4 -Dlanguage=Java .tmp/grammar/EasyScript.g4
+
+            # Compile the grammar
+            JAVA_FILES=$(find "$PROJECT_DIR"/.tmp/grammar -name "*.java" -print0 | tr '\0' ' ')
+            JAVA_FILES=${JAVA_FILES//"$PROJECT_DIR"\//}
+            javac -cp /usr/local/lib/antlr4-tool.jar -d .tmp/grammar/target $JAVA_FILES
+
+            # Run the 'antlr4-parse' command
+            echo "Write your input and press Ctrl+D to finish."
+            antlr4_parse EasyScript easy -tree
+
+            exit 0
+            ;;
+        *)
+            echo "Error: Unknown command '$command_requested'."
+            echo "Use -h or --help for usage information."
+            exit 1
+            ;;
+    esac
 }
 
 # Prepare temporary directory
 mkdir -p "$PROJECT_DIR/.tmp"
 
-if [ "$#" -ne 1 ]; then
-    help
-    exit 1
-fi
-
-if [ "$1" == "help" ]; then
-    help
-    exit 0
-fi
-
-if [ "$1" == "generate:csharp" ]; then
-    prepare_docker
-    prepare_grammar
-
-    # Generate the grammar as C# files
-    antlr4 -Dlanguage=CSharp -o .tmp/grammar/csharp .tmp/grammar/EasyScript.g4
-
-    echo "C# grammar files have been generated in '.tmp/grammar/csharp'."
-    exit 0
-fi
-
-if [ "$1" == "tree" ]; then
-    prepare_docker
-    prepare_grammar
-
-    # Generate the grammar as Java files
-    antlr4 -Dlanguage=Java .tmp/grammar/EasyScript.g4
-
-    # Compile the grammar
-    JAVA_FILES=$(find "$PROJECT_DIR"/.tmp/grammar -name "*.java" -print0 | tr '\0' ' ')
-    JAVA_FILES=${JAVA_FILES//"$PROJECT_DIR"\//}
-    javac -cp /usr/local/lib/antlr4-tool.jar -d .tmp/grammar/target $JAVA_FILES
-
-    # Run the 'antlr4-parse' command
-    echo "Write your input and press Ctrl+D to finish."
-    antlr4_parse EasyScript easy -tree
-
-    exit 0
-fi
-
-echo "Invalid command '$1'."
-echo "Run '$0 help' for usage."
-exit 1
+parse_arguments "$@"
